version: '3'
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MONGODB_URI: "mongodb://mongodb_container:27017/unichatboot_db" # Passing MONGODB_URI as an ARG during build
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongodb_container:27017/unichatboot_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - API_URL=http://localhost:3000
      - NODE_ENV=production
    networks:
      - MONGO
  
  
  mongo:
    container_name: mongodb_container
    image: mongo:latest
    volumes:
      - MONGO_DATA:/data/db
      - MONGO_CONFIG:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - MONGO
networks:
  MONGO:
    name: MONGO
volumes:
  MONGO_DATA:
  MONGO_CONFIG:

